// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrFJXyd71ok3DFZWESfO5LNJrTv6HSpRw',
    appId: '1:793347691756:web:dbfcdc6934f5f743b281c9',
    messagingSenderId: '793347691756',
    projectId: 'mp-db-7db98',
    authDomain: 'mp-db-7db98.firebaseapp.com',
    databaseURL: 'https://mp-db-7db98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mp-db-7db98.appspot.com',
    measurementId: 'G-634HXQ6WHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByqduS1eLsVp391NaLtg84qwwjtxTK7qQ',
    appId: '1:793347691756:android:c2831948f4e41903b281c9',
    messagingSenderId: '793347691756',
    projectId: 'mp-db-7db98',
    databaseURL: 'https://mp-db-7db98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mp-db-7db98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzPzu3fci2lx1maTqQKSZy_VcywsLBhUE',
    appId: '1:793347691756:ios:e902ad1e13dd5930b281c9',
    messagingSenderId: '793347691756',
    projectId: 'mp-db-7db98',
    databaseURL: 'https://mp-db-7db98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mp-db-7db98.appspot.com',
    iosClientId: '793347691756-2fhr2s1mh9up7fab3g2d6k8aohq3vuln.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzPzu3fci2lx1maTqQKSZy_VcywsLBhUE',
    appId: '1:793347691756:ios:e902ad1e13dd5930b281c9',
    messagingSenderId: '793347691756',
    projectId: 'mp-db-7db98',
    databaseURL: 'https://mp-db-7db98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mp-db-7db98.appspot.com',
    iosClientId: '793347691756-2fhr2s1mh9up7fab3g2d6k8aohq3vuln.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
